
import { ThemeType, Language } from './types';

export const UI_STRINGS = {
  [Language.ES]: {
    projects: "Proyectos",
    skills: "Habilidades",
    work_experience: "Experiencia",
    contact: "Contacto",
    admin: "Admin CMS",
    hero_impact: "Diseño Impacto",
    hero_build: "Construyo Futuro",
    available: "Disponible para nuevos retos",
    view_work: "Ver Mi Trabajo",
    download_cv: "CV",
    cv_url: "URL del Curriculum (PDF/Drive)",
    view_site: "Ver Sitio Público",
    expertise: "Expertise Técnico",
    expertise_desc: "Domino las herramientas para crear soluciones digitales de alto impacto.",
    footer_built: "Construido con Gemini & PostgreSQL",
    edit: "Editar",
    delete: "Eliminar",
    save: "Guardar",
    cancel: "Cancelar",
    processing: "Procesando...",
    login_title: "Acceso Admin",
    login_desc: "Gestiona tu portafolio profesional",
    username: "Usuario",
    password: "Contraseña",
    login_btn: "Entrar al Panel",
    dashboard: "Dashboard",
    portfolio: "Portafolio",
    themes: "Temas",
    users: "Usuarios",
    logout: "Salir",
    case_study: "Caso de Estudio",
    explore: "Explorar Proyecto",
    visit_live: "Visitar Sitio Live",
    profile: "Perfil",
    name: "Nombre",
    email: "Email",
    role_label: "Cargo",
    bio_label: "Biografía",
    new_project: "Nuevo Proyecto",
    new_skill: "Nueva Habilidad",
    new_work: "Nueva Experiencia",
    skill_name: "Nombre de Habilidad",
    skill_level: "Nivel (0-100)",
    skill_category: "Categoría",
    title: "Título",
    description: "Descripción Corta",
    long_description: "Descripción Detallada",
    tags: "Etiquetas (separadas por coma)",
    image_url: "URL de Imagen",
    project_link: "Link del Proyecto",
    user_management: "Gestión de Usuarios",
    role_select: "Rol de Usuario",
    add_user: "Añadir Usuario",
    company: "Empresa",
    location: "Ubicación",
    dates: "Fechas (ej: 2020 - 2023)",
    experience_title: "Trayectoria Profesional"
  },
  [Language.EN]: {
    projects: "Projects",
    skills: "Skills",
    work_experience: "Experience",
    contact: "Contact",
    admin: "Admin CMS",
    hero_impact: "Impact Design",
    hero_build: "Building Future",
    available: "Available for new challenges",
    view_work: "View My Work",
    download_cv: "CV",
    cv_url: "Curriculum URL (PDF/Drive)",
    view_site: "View Public Site",
    expertise: "Technical Expertise",
    expertise_desc: "Mastering tools to create high-impact digital solutions.",
    footer_built: "Built with Gemini & PostgreSQL",
    edit: "Edit",
    delete: "Delete",
    save: "Save",
    cancel: "Cancel",
    processing: "Processing...",
    login_title: "Admin Access",
    login_desc: "Manage your professional portfolio",
    username: "Username",
    password: "Password",
    login_btn: "Enter Panel",
    dashboard: "Dashboard",
    portfolio: "Portfolio",
    themes: "Themes",
    users: "Users",
    logout: "Logout",
    case_study: "Case Study",
    explore: "Explore Project",
    visit_live: "Visit Live Site",
    profile: "Profile",
    name: "Name",
    email: "Email",
    role_label: "Role",
    bio_label: "Biography",
    new_project: "New Project",
    new_skill: "New Skill",
    new_work: "New Experience",
    skill_name: "Skill Name",
    skill_level: "Level (0-100)",
    skill_category: "Category",
    title: "Title",
    description: "Short Description",
    long_description: "Detailed Description",
    tags: "Tags (comma separated)",
    image_url: "Image URL",
    project_link: "Project Link",
    user_management: "User Management",
    role_select: "User Role",
    add_user: "Add User",
    company: "Company",
    location: "Location",
    dates: "Dates (e.g., 2020 - 2023)",
    experience_title: "Professional Journey"
  }
};

export const THEME_CONFIGS: Record<ThemeType, any> = {
  [ThemeType.MODERN]: { isDark: false, bg: 'bg-slate-50', text: 'text-slate-900', accent: 'bg-indigo-600', accentText: 'text-indigo-600', card: 'bg-white', border: 'border-slate-200', font: 'font-sans' },
  [ThemeType.DARK]: { isDark: true, bg: 'bg-zinc-950', text: 'text-zinc-100', accent: 'bg-emerald-500', accentText: 'text-emerald-400', card: 'bg-zinc-900', border: 'border-zinc-800', font: 'font-sans' },
  [ThemeType.MINIMAL]: { isDark: false, bg: 'bg-white', text: 'text-neutral-800', accent: 'bg-black', accentText: 'text-black', card: 'bg-white', border: 'border-neutral-100', font: 'font-sans' },
  [ThemeType.CYBERPUNK]: { isDark: true, bg: 'bg-purple-950', text: 'text-cyan-400', accent: 'bg-fuchsia-600', accentText: 'text-fuchsia-400', card: 'bg-purple-900/40', border: 'border-cyan-500/30', font: 'font-mono' },
  [ThemeType.SUNSET]: { isDark: false, bg: 'bg-orange-50', text: 'text-orange-950', accent: 'bg-rose-500', accentText: 'text-rose-600', card: 'bg-white', border: 'border-orange-200', font: 'font-sans' },
  [ThemeType.RETRO]: { isDark: false, bg: 'bg-stone-200', text: 'text-stone-800', accent: 'bg-orange-700', accentText: 'text-orange-800', card: 'bg-stone-100', border: 'border-stone-400', font: 'font-serif' },
  [ThemeType.FOREST]: { isDark: true, bg: 'bg-emerald-950', text: 'text-emerald-50', accent: 'bg-lime-500', accentText: 'text-lime-400', card: 'bg-emerald-900', border: 'border-emerald-800', font: 'font-sans' },
  [ThemeType.MIDNIGHT]: { isDark: true, bg: 'bg-slate-950', text: 'text-amber-50', accent: 'bg-amber-500', accentText: 'text-amber-500', card: 'bg-slate-900', border: 'border-slate-800', font: 'font-serif' },
  [ThemeType.VAPORWAVE]: { isDark: false, bg: 'bg-pink-100', text: 'text-teal-900', accent: 'bg-teal-400', accentText: 'text-pink-600', card: 'bg-white', border: 'border-pink-300', font: 'font-mono' },
  [ThemeType.NEO_GLASS]: { isDark: false, bg: 'bg-gradient-to-br from-blue-50 to-indigo-100', text: 'text-slate-800', accent: 'bg-indigo-500', accentText: 'text-indigo-600', card: 'bg-white/70 backdrop-blur-md shadow-xl border-white/40', border: 'border-white/20', font: 'font-sans' },
  [ThemeType.DEEP_NAVY]: { isDark: true, bg: 'bg-[#0a0f1d]', text: 'text-blue-50', accent: 'bg-blue-600', accentText: 'text-blue-400', card: 'bg-[#121a2e]', border: 'border-blue-900/30', font: 'font-sans' },
  [ThemeType.ROSE_GOLD]: { isDark: false, bg: 'bg-[#fdfcfb]', text: 'text-[#4a3f35]', accent: 'bg-[#c5a386]', accentText: 'text-[#a68266]', card: 'bg-white shadow-md', border: 'border-[#e8e2dc]', font: 'font-serif' },
  [ThemeType.NORDIC]: { isDark: false, bg: 'bg-[#f3f4f6]', text: 'text-[#2d3436]', accent: 'bg-[#636e72]', accentText: 'text-[#0984e3]', card: 'bg-white border-0 shadow-sm', border: 'border-transparent', font: 'font-sans' },
  [ThemeType.SLATE_PROFESSIONAL]: { isDark: true, bg: 'bg-slate-900', text: 'text-slate-200', accent: 'bg-cyan-500', accentText: 'text-cyan-400', card: 'bg-slate-800', border: 'border-slate-700', font: 'font-sans' },
  
  // Temas inspirados en VS Code / IDEs
  [ThemeType.VS_CODE_DARK]: { isDark: true, bg: 'bg-[#1e1e1e]', text: 'text-[#cccccc]', accent: 'bg-[#007acc]', accentText: 'text-[#007acc]', card: 'bg-[#252526]', border: 'border-[#333333]', font: 'font-mono' },
  [ThemeType.VS_CODE_LIGHT]: { isDark: false, bg: 'bg-[#ffffff]', text: 'text-[#333333]', accent: 'bg-[#007acc]', accentText: 'text-[#007acc]', card: 'bg-[#f3f3f3]', border: 'border-[#cccccc]', font: 'font-mono' },
  [ThemeType.GITHUB_DARK]: { isDark: true, bg: 'bg-[#0d1117]', text: 'text-[#c9d1d9]', accent: 'bg-[#2f81f7]', accentText: 'text-[#2f81f7]', card: 'bg-[#161b22]', border: 'border-[#30363d]', font: 'font-sans' },
  [ThemeType.GITHUB_LIGHT]: { isDark: false, bg: 'bg-[#ffffff]', text: 'text-[#24292f]', accent: 'bg-[#2da44e]', accentText: 'text-[#2da44e]', card: 'bg-[#f6f8fa]', border: 'border-[#d0d7de]', font: 'font-sans' },
  [ThemeType.MONOKAI]: { isDark: true, bg: 'bg-[#272822]', text: 'text-[#f8f8f2]', accent: 'bg-[#f92672]', accentText: 'text-[#f92672]', card: 'bg-[#3e3d32]', border: 'border-[#49483e]', font: 'font-mono' },
  [ThemeType.DRACULA]: { isDark: true, bg: 'bg-[#282a36]', text: 'text-[#f8f8f2]', accent: 'bg-[#bd93f9]', accentText: 'text-[#bd93f9]', card: 'bg-[#44475a]', border: 'border-[#6272a4]', font: 'font-mono' },
  [ThemeType.ONE_DARK]: { isDark: true, bg: 'bg-[#282c34]', text: 'text-[#abb2bf]', accent: 'bg-[#61afef]', accentText: 'text-[#61afef]', card: 'bg-[#21252b]', border: 'border-[#181a1f]', font: 'font-sans' },
  [ThemeType.SOLARIZED_LIGHT]: { isDark: false, bg: 'bg-[#fdf6e3]', text: 'text-[#657b83]', accent: 'bg-[#268bd2]', accentText: 'text-[#268bd2]', card: 'bg-[#eee8d5]', border: 'border-[#d33682]/10', font: 'font-serif' },
  [ThemeType.SOLARIZED_DARK]: { isDark: true, bg: 'bg-[#002b36]', text: 'text-[#839496]', accent: 'bg-[#268bd2]', accentText: 'text-[#268bd2]', card: 'bg-[#073642]', border: 'border-[#586e75]/20', font: 'font-serif' },
  [ThemeType.PANDA_SYNTAX]: { isDark: true, bg: 'bg-[#292a2b]', text: 'text-[#e6e6e6]', accent: 'bg-[#ff75b5]', accentText: 'text-[#ff75b5]', card: 'bg-[#313233]', border: 'border-[#3e3f40]', font: 'font-mono' }
};

export const INITIAL_DATA: any = {
  name: "Alex Dev",
  role: {
    es: "Ingeniero Full-Stack Senior",
    en: "Senior Full-Stack Engineer"
  },
  bio: {
    es: "Apasionado por construir aplicaciones web escalables y experiencias de usuario intuitivas. Especializado en React, Node.js e Infraestructura Cloud.",
    en: "Passionate about building scalable web applications and intuitive user experiences. Specialized in React, Node.js, and Cloud Infrastructure."
  },
  avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=400",
  cvUrl: "",
  email: "alex@example.com",
  github: "https://github.com",
  linkedin: "https://linkedin.com",
  theme: ThemeType.MODERN,
  projects: [
    {
      id: "1",
      title: { es: "Plataforma E-Commerce", en: "E-Commerce Platform" },
      description: { es: "Una tienda online completa construida con React y Node.js.", en: "A full-featured online store built with React and Node.js." },
      longDescription: {
        es: "Esta solución integral cuenta con un CMS headless, integración de Stripe en tiempo real y un sistema sofisticado de gestión de inventario.",
        en: "This comprehensive e-commerce solution features a headless CMS, real-time Stripe integration, and a sophisticated inventory management system."
      },
      image: "https://images.unsplash.com/photo-1557821552-17105176677c?auto=format&fit=crop&q=80&w=1000",
      tags: ["React", "Express", "PostgreSQL", "Stripe"],
      link: "#"
    }
  ],
  skills: [
    { id: "s1", name: "React", level: 95, category: "Frontend" },
    { id: "s2", name: "TypeScript", level: 90, category: "Frontend" },
    { id: "s3", name: "Node.js", level: 85, category: "Backend" }
  ],
  workExperience: []
};
